# generated by pkgs_update.exs (2019-07-23)
import(fetchTarball {
  name = "nixpkgs-unstable_2019-07-23";
  url = "https://github.com/NixOS/nixpkgs-channels/archive/3d84cffe95527abf139bd157befab677ba04a421.tar.gz";
  sha256 = "161yyl91bi72xqwl26nwm0j3b58h9h4yff7lc9rnf25x1jq5d555";
}) {}
