# generated by pkgs_update.exs (2021-09-22)
import
  (fetchTarball {
    name = "nixpkgs-unstable_2021-09-22";
    url = "https://github.com/NixOS/nixpkgs/archive/e0ce3c683ae677cf5aab597d645520cddd13392b.tar.gz";
  })
{ }
