# generated by pkgs_update.exs (2021-05-16)
import(fetchTarball {
  name = "nixos-unstable-small_2021-05-16";
  url = "https://github.com/NixOS/nixpkgs/archive/9b92a817238eae3e2f3dfbc8d205a5a1c0d1461c.tar.gz";
}) {}
